# Base image PHP
FROM php:8.2-fpm

# Install system dependencies dan GD
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd \
    && docker-php-ext-install pdo pdo_mysql

# Install Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Set working directory
WORKDIR /var/www/html

# Copy project files
COPY . .

# Install composer dependencies
RUN composer install --optimize-autoloader --no-interaction

# Expose port untuk Laravel serve
EXPOSE 8000

# Jalankan artisan serve
CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
